auto: true

#markdown: rdiscount
highlighter: 'rouge'
#paginate: 8
permalink: /:title

title: wt'blog
url: http://sun035.github.io
feed: /atom.xml
author_info: <a href="http://sun035.github.io/">Mukosame</a>
